name: Tests Unitaires

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

        env:
          SSH_PASSWORD: ${{secrets.SSH_PASSWORD}}

      - name: Run tests
        run: python -m unittest test_addition.py
        run: sshpass -p "$SSH_PASSWORD" scp addition.py ubuntu@20.56.74.49:/home/ubuntu/mt
